// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { ApplicationDetailsComponent } from '@app/view/application/application-details.component';
import { ApplicationDetailsVarsForm } from '@app/view/application/application-details.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from "@shared/loader/loader.component";

@Component({
  selector: 'app-application-details',
  templateUrl: './application-details.component.html',
  styleUrls: ['./application-details.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    LoaderComponent,
  ],
})
export class ApplicationDetailsImplComponent extends ApplicationDetailsComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: ApplicationDetailsVarsForm): ApplicationDetailsVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }
}