// Generated by andromda-angular cartridge (controller\controller.impl.ts.vsl) Can Modify
import { Injectable } from '@angular/core';
import { ApplicationController } from '@app/controller/application/application-controller';

@Injectable()
export class ApplicationControllerImpl extends ApplicationController {

    constructor() {
        super();
    }

}
