server:
  port: ${PORT:8680}
spring:
  mvc:
    format:
      date: iso
      date-time: iso
      time: HH:mm:ss
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  security:
    oauth2:
      client:
        registration:
          keycloak:
            client-id: ${CLIENT_ID:cfpso-api}
            provider: keycloak
            scope: openid, profile, email
        provider:
          keycloak:
            issuer-uri: ${AUTH_URL:http://localhost:8970}/realms/${REALM:cfpso}
            user-name-attribute: preferred_username
      resourceserver:
        jwt:
          issuer-uri: ${AUTH_URL:http://localhost:8970}/realms/${REALM:cfpso}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: ${GENRATE_DDL:false}
    hibernate:
      ddl-auto: update
    show-sql: ${SHOW_SQL:false}
  liquibase:
    enabled: false
  data:
    redis:
      host: ${REDIS_HOST:localhost}
      port: ${REDIS_PORT:6379}
      password: ${REDIS_PASSWORD}
      timeout: 100
management:
  endpoint:
    health:
      show-details: always
    metrics:
      access: READ_ONLY
    prometheus:
      access: READ_ONLY
  endpoints:
    web:
      base-path: /actuator
      exposure:
        include: '*'
  metrics:
    tags:
      application: ${spring.application.name}
      version: ${spring.application.version}
rate-limiting:
  tokens: ${RATE_LIMIT:20}
