// Generated by andromda-angular cartridge (view\view.component.imp.ts.vsl) CAN EDIT!
import { Component } from '@angular/core';
import { EditAccessPointComponent } from '@app/view/access/edit-access-point.component';
import { EditAccessPointVarsForm } from '@app/view/access/edit-access-point.component';
import { MatRadioChange } from '@angular/material/radio';
import { MatCheckboxChange } from '@angular/material/checkbox';
import { CommonModule } from '@angular/common';
import { FormsModule, ReactiveFormsModule } from '@angular/forms';
import { TranslateModule } from '@ngx-translate/core';
import { MaterialModule } from '@app/material.module';
import { TableComponent } from '@app/components/table/table.component';
import { LoaderComponent } from "@shared/loader/loader.component";
import { AccessPointSearchImplComponent } from '@app/components/access/access-point-search-impl.component';

@Component({
  selector: 'app-edit-access-point',
  templateUrl: './edit-access-point.component.html',
  styleUrls: ['./edit-access-point.component.scss'],
  standalone: true,
  imports: [
    CommonModule,
    FormsModule,
    ReactiveFormsModule,
    TranslateModule,
    MaterialModule,
    TableComponent,
    LoaderComponent,
    AccessPointSearchImplComponent,
  ],
})
export class EditAccessPointImplComponent extends EditAccessPointComponent {

    constructor() {
        super();
    }

    override beforeOnInit(form: EditAccessPointVarsForm): EditAccessPointVarsForm{     
        return form;
    }

    doNgOnDestroy(): void {
    }
}