// Generated by andromda-angular cartridge (service\service.impl.ts.vsl) CAN EDIT
import { Injectable, inject } from '@angular/core';
import { Observable } from 'rxjs';
import { ApplicationDTO } from '@app/model/bw/co/roguesystems/tau/application/application-dto';
import { HttpClient } from '@angular/common/http';
import { Page } from '@app/model/page.model';
import { SearchObject } from '@app/model/search-object';

@Injectable({
  providedIn: 'root'
})
export class ApplicationApi {
    
    protected path = '/application';

    private http = inject(HttpClient);

    public findById(id: string | any ): Observable<ApplicationDTO | any> {

        return this.http.get<ApplicationDTO | any>(this.path + `/${id}`);
    }

    public getAll(): Observable<ApplicationDTO[] | any[]> {

        return this.http.get<ApplicationDTO[] | any[]>(this.path);
    }

    public getAllPaged(pageNumber: number | any , pageSize: number | any ): Observable<ApplicationDTO | any> {

        return this.http.get<ApplicationDTO | any>(this.path + `/paged?pageNumber=${pageNumber}&pageSize=${pageSize}`);
    }

    public pagedSearch(criteria: SearchObject<string> | any ): Observable<ApplicationDTO | any> {

        return this.http.post<ApplicationDTO | any>(this.path + `/search/paged`, criteria);
    }

    public remove(id: string | any ): Observable<boolean | any> {

        return this.http.delete<boolean | any>(this.path + `/${id}`);
    }

    public save(application: ApplicationDTO | any ): Observable<ApplicationDTO | any> {

        return this.http.post<ApplicationDTO | any>(this.path, application);
    }

    public search(criteria: string | any ): Observable<ApplicationDTO[] | any[]> {

        return this.http.get<ApplicationDTO[] | any[]>(this.path + `/search?criteria=${criteria}`);
    }

}
